### PR TITLE
Update README with detailed instructions

### PR DESCRIPTION
**Pull request by jodizzle**
I've tried to make the instructions highly detailed and clear (and pretty looking), but I think they should definitely be scrutinized.

It would be nice to have a "Debugging" or "Testing" or "Use" section, though it might be better to wait on that until MeleeAI is more stable.

### CODE REVIEW

**Comment by sepharoth213** [comment]
This stuff is starting to get out of hand, I think we should move to the wiki for setup instructions ASAP.

**Comment by jodizzle** [comment]
I think there are a couple of different options we should consider.  Personally I would rather have the documentation available and sitting around in the main repository as opposed to a separate repository-like wiki, which seems to be what Github wikis are.

If the README becomes too long, we could create a table of contents that better organizes the information and/or separate the README.md into several markdown files (e.g., INSTALLATION.md, CONTRIBUTING.md) that are linked together.  If we want the docs to be better presented, we can use a `gh-pages` branch or something like [Read the Docs](https://readthedocs.org/).

Also, the length of the setup instructions will hopefully decrease as time goes on and MeleeAI automates more of the process.  For now, I don't think the length is too atrocious.

**Comment by sepharoth213** [comment]
I don't agree. I feel the readme should have an overview of what MeleeAI is, and can link to the wiki for setup instructions. Setup has already diverged in some places between Linux and OSX: if/when Windows support happens then setup there will be even more divergent. We also already have many troubleshooting tips that should be documented; doing so in the readme would just be bloat.

My feeling is that if we ever want to put information into the wiki, we might as well move the setup instructions there as well.

**Comment by jodizzle** [comment]
I mostly just like the idea of having the docs versioned alongside the code.  I would hazard a guess that most users and potential contributors would be more comfortable and familiar with editing a `README.md` as opposed to wiki pages.

If we did use wikis, I think we should use a mixed method similar to what [Dolphin](https://github.com/dolphin-emu/dolphin) seems to do.  The README has an overview, several sets of instructions and important links, whereas the [wiki](https://github.com/dolphin-emu/dolphin) has repetitions of this information together with more specific content.

[Here's](https://help.github.com/categories/wiki/) a page that provides information on how to setup and manage a wiki.

**Comment by sepharoth213** [comment]
GitHub wikis are markdown as well. Keeping the docs versioned alongside the code makes merging documentation across branches less tractable I feel: imagine if we had a develop branch that supported OSX and a master branch that didn't, but then a Windows branch where we experimented with Windows support. READMEs would become a mess. I think the complexity of getting MeleeAI running warrants a wiki page, when we have a tool for automating some of the setup and it can be as easily described as building Dolphin is, then it can totally be here in its entirety.

**Pull request merged**
