### PR TITLE
Clean and format code

### PR DESCRIPTION
**Pull request by jodizzle**
This is a cleaner version of #9 (I had to re-branch and rebase).
Continuing the discussion from #9:
I aligned the class members and re-arranged them so `public` appears before `private`.  Since the code seems pretty readable to me I didn't add the line spaces or move the curly braces in the way that @sepharoth213 recommended.  To take an example from the code, we have
```C++
class DefensiveAI : public AI {
public:
    DefensiveAI();
    ~DefensiveAI();

    void MakeMove();
    void WaitForTrigger();
    bool TriggerEvents();
//...
```
as the current formatting versus
```C++
class DefensiveAI : public AI {

public:
    DefensiveAI();
    ~DefensiveAI();

    void MakeMove();
    void WaitForTrigger();
    bool TriggerEvents();
//...
```
and
```C++
class DefensiveAI : public AI 
{
public:
    DefensiveAI();
    ~DefensiveAI();

    void MakeMove();
    void WaitForTrigger();
    bool TriggerEvents();
//...
```
as the alternative formats.  I think the current one looks fine (though personally would prefer indentation, though that's in the past), but it's open to interpretation.  Fairly minor issue overall, which is why we should spend as long as possible discussing it :grin:

### CODE REVIEW

**Comment by sepharoth213** [comment]
Dolphin uses brackets on the new line: https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#classes-and-structs

**Comment by sepharoth213** [comment]
Also this: http://programmers.stackexchange.com/a/2786
"If you're going to make a visual break, you may as well do it with a brace. Then your visual breaks become consistent, too."

**Comment by sepharoth213** [comment]
The bracket debate can be settled in the future, for now, enforcing the spacing is more important.

**Comment by jodizzle** [comment]
Sounds good.  It might be a good idea to find a C++ linter/formatter that we mostly agree with and rely on it to maintain consistency.  Going through the code manually was a bit of a hassle.

**Pull request merged**
