### PR TITLE
Clean and format code

### PR DESCRIPTION
**Pull request by jodizzle**
I spread these changes out over a number of commits so that I could be clearer about what changed.  Overall, it's a number of minor changes that should make the code more readable.  The biggest change is the shift from two spaces to four spaces for indentation.

### CODE REVIEW

**Comment by sepharoth213** [comment]
There are conflicts, can you merge them?

**Comment by sepharoth213** [comment]
Also, w/r/t spacing, I think it's cleaner to keep public and private at the same tab length as the class.

Another thing to watch is to make sure that public and private order is consistent, but going as far as dictating member order might be too much.

I think it's pretty standard to have classes defined like this:

```cpp
class Example {

public:
    Example();
    void ExampleMethod();
    void ExampleMethod2();

    float exampleMember;
    int exampleMember2;

private:
    int m_examplePrivateMember;
    float m_examplePrivateMember2;
}
```

On a personal note, opening brackets currently never get a new line, and I prefer it to be the other way. I feel this is significantly less important than moving to 4 spaces, but it's something to decide on/enforce for future code.

**Comment by jodizzle** [comment]
I did the merge, and I've fixed the indentation with the `public` and `private` keywords locally.  This might sound silly, but are you attached to the line space between `class Example {` and the first keyword?  I can make a decision on it in my next commit.

Personally, I don't like giving opening brackets a new line, though I haven't worked with much C++ code before so I don't know if there are any particular advantages.  Also, the current order of all the class members (unless I'm missing one) seem to be `private`/`protected` and then `public`, which I'm thinking is fine, so I've left it like that

**Comment by sepharoth213** [comment]
The order should be public first. When reading a file for the first time you do not want to be looking through the stuff that doesn't matter to get to the stuff that does.

I'm really attached to the line space because I think that improves readability, but not having to deal with that issue at all is one of the bigger benefits behind having the bracket on a new line. I personally also think it makes it easier to scan a file and find where a bracket opens, but that's subjective.

```c++
if(true){
    cout << "this";
}

if(true){

    cout << "this";
}

if(true)
{
    cout << "or this";
}
```

I personally think the first one of those is really difficult to read.

**Comment by jodizzle** [comment]
I noticed an issue with my commit history on this branch (first commit is a duplicate of one in master) so I'm gonna close this pull request and open a new one.

**Pull request closed without merging**
